# comentario -> para executar digite make 

all: compile
	
compile:

	gcc -o 11 1fork_cria_processos.c
	gcc -o 12 1fork_cria_processos_var_local.c

	gcc -o 21  2fork_incrementa_vetor.c

	gcc -o 31 3fork_soma_vetor_erro.c
	gcc -o 32 3fork_soma_vetor_mem_comp.c
	gcc -o 33 3fork_soma_vetor_mem_comp_aux.c
	
	@echo "Compilaçao concluida"

clean:
	rm -rf *.out
	rm -rf ? 
	rm -rf ??
	
limpa:
	clear




