# comentario -> para executar digite make 

all: compile
	
compile:

	gcc -o 11 0scanf.c	
	gcc -o 12 0pid.c
	gcc -o 13 0size_of_var.c

	gcc -o 21 0incrementa_vetor.c
	gcc -o 22 0soma_vetor.c
	gcc -o 23 0soma_vetor_max_size.c

	gcc -o 31 0ponteiro.c
	gcc -o 32 0ponteiro-casting.c
	gcc -o 33 0ponteiro-void.c

	gcc -o 34 0soma_vetor_ponteiro.c
 
	gcc -o 41 0-argc-argv.c           
	
	g++ -o 1c 1comando.c
	
	@echo "Compilaçao concluida"



clean:
	rm -rf *.out
	rm -rf ? 
	rm -rf ??
	
limpa:
	clear




